name: 'Amazon ECS "Run Task" Action'
author: "Uturn Data Solutions"
description: "Runs a standalone Amazon ECS task (EC2 or Fargate)"
branding:
  icon: "cloud"
  color: "blue"
inputs:
  task-definition:
    description: "The name of ECS task definition"
    required: true
  cluster:
    description: "The name of the ECS cluster. Will default to the 'default' cluster"
    required: true
  count:
    description: "The count of tasks to run. Will default to the 1"
    required: true
  launch-type:
    description: "The infrastructure to run your standalone task on."
    required: false
  network-configuration:
    description: "The network configuration for the service. This parameter is required for task definitions that use the awsvpc network mode to receive their own elastic network interface, such as those run on Fargate."
    required: false
  started-by:
    description: "The value of the task started-by"
    required: false
  wait-for-finish:
    description: "Whether to wait for tasks to reach stopped state. Will default to not waiting"
    required: false
  wait-for-minutes:
    description: "How long to wait for the task reach stopped state, in minutes (default: 30 minutes, max: 6 hours)."
    required: false
outputs:
  task-definition-arn:
    description: "The ARN of the registered ECS task definition"
  task-arn:
    description: "The ARN of the ECS task"
runs:
  using: "node12"
  main: "dist/index.js"
